name: CI/CD Pipeline

on:
  push:
    branches:
      - main
    paths:
      - 'services/inventory-service/**'
      - 'services/ui/**'
  pull_request:
    branches:
      - main
    paths:
      - 'services/inventory-service/**'
      - 'services/ui/**'
  workflow_dispatch:

jobs:
  build-and-test-inventory-service:
    name: Build and Test Inventory Service
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'workflow_dispatch' ||
      contains(github.event.head_commit.message, 'services/inventory-service')

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run tests for Inventory Service
        run: ./gradlew :services:inventory-service:test

      - name: Build Inventory Service
        run: ./gradlew :services:inventory-service:build

      - name: Build Docker image for Inventory Service
        run: docker build -t csh628/inventory-service:latest -f services/inventory-service/Dockerfile .

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Push Docker image to Docker Hub
        run: docker push csh628/inventory-service:latest

  build-and-test-ui-service:
    name: Build and Test UI Service
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'workflow_dispatch' ||
      contains(github.event.head_commit.message, 'services/ui')

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build UI Service
        run: ./gradlew :services:ui:build

      - name: Build Docker image for UI Service
        run: docker build -t csh628/ui-service:latest -f services/ui/Dockerfile .

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Push Docker image to Docker Hub
        run: docker push csh628/ui-service:latest
