name: CI/CD Pipeline

on:
  push:
    branches:
      - main
    paths:
      - 'services/inventory-service/**'
      - 'services/ui/**'
  pull_request:
    branches:
      - main
    paths:
      - 'services/inventory-service/**'
      - 'services/ui/**'
  workflow_dispatch:

jobs:
  build-and-test-inventory-service:
    name: Build and Test Inventory Service
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'workflow_dispatch' ||
      contains(github.event.head_commit.message, 'services/inventory-service')

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run tests for Inventory Service
        run: ./gradlew :services:inventory-service:test

      - name: Build Inventory Service
        run: ./gradlew :services:inventory-service:build

      - name: Package Docker image for Inventory Service
        run: docker build -t inventory-service:latest -f services/inventory-service/Dockerfile .

      - name: Save Docker image to tar file
        run: docker save -o inventory-service.tar inventory-service:latest

      - name: Push Docker image to EC2
        uses: appleboy/scp-action@v0.1.4
        with:
          host: 15.164.104.244
          username: minikube
          password: springdemo1234
          source: "inventory-service.tar"
          target: "/home/minikube/inventory-service.tar"

      - name: Deploy Inventory Service on EC2 Minikube
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: 15.164.104.244
          username: minikube
          password: springdemo1234
          script: |
            docker load -i /home/minikube/inventory-service.tar
            minikube image load inventory-service:latest --profile=minikube
            kubectl apply -f /home/minikube/services/inventory-service/inventory-deployment.yaml

  build-and-test-ui-service:
    name: Build and Test UI Service
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'workflow_dispatch' ||
      contains(github.event.head_commit.message, 'services/ui')

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build UI Service
        run: ./gradlew :services:ui:build

      - name: Package Docker image for UI Service
        run: docker build -t ui-service:latest -f services/ui/Dockerfile .

      - name: Push Docker image to EC2
        uses: appleboy/scp-action@v0.1.4
        with:
          host: 15.164.104.244
          username: minikube
          password: springdemo1234
          source: "ui-service:latest"
          target: "/home/minikube/ui-service:latest"

      - name: Deploy UI Service on EC2 Minikube
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: 15.164.104.244
          username: minikube
          password: springdemo1234
          script: |
            docker load -i /home/minikube/ui-service:latest
            minikube image load ui-service:latest --profile=minikube
            kubectl apply -f /home/minikube/services/ui/ui-deployment.yaml
